# ==================================================
# MARS API V1 - Pure GraphQL Configuration
# ==================================================
# This is the pure GraphQL configuration for MARS API V1
#
# Major changes in V1:
# 1. New D1 database with 15 tables for authentication and analytics
# 2. API key-based authentication system
# 3. Scheduled cron jobs for data synchronization
# 4. Permission-based access control with subscription tiers
# 5. Comprehensive rate limiting and usage tracking
#
# Setup Instructions:
# 1. Copy this file to wrangler.toml
# 2. Replace YOUR_*_HERE placeholders with actual values
# 3. Create D1 databases: wrangler d1 create d1-dex-database
# 4. Run migrations: npm run migrate:local
# 5. Initialize data: npm run db:init
# 6. Set secrets: wrangler secret put KEY && wrangler secret put SUBGRAPH_AUTH_TOKEN
# 7. Deploy subgraph to The Graph network
# 8. Update SUBGRAPH_URL in vars section
# ==================================================

name = "mars-backend-serverless"
main = "src/index.ts"
compatibility_date = "2025-06-20"
compatibility_flags = ["nodejs_compat"]

# Replace with your Cloudflare account ID
account_id = "ec9b597fa02615ca6a0e62b7ff35d0cc"

# ✅ Scheduled jobs for data synchronization - Multiple cron triggers
[triggers]
crons = [
  "*/1 * * * *",    # Every 1 minute - Cache warming & container heartbeat
  "*/10 * * * *",   # Every 10 minutes - Vault historical data collection
  "0 2 * * 7"       # Every Sunday at 2 AM - Weekly cleanup (0 = Sunday)
]

# ✅ Logging configuration - Enable Workers logs
# This enables automatic logging in Cloudflare Workers dashboard
[observability]
enabled = true

# ✅ Environment variables - Pure GraphQL configuration
[vars]
# Basic configuration
NODE_ENV = "production"

# Logging configuration
LOG_LEVEL = "info"  # debug, info, warn, error
ENABLE_CONSOLE_LOGS = "true"
ENABLE_STRUCTURED_LOGS = "true"

# GraphQL configuration
SUBGRAPH_URL = "https://api.studio.thegraph.com/query/114739/enty-square-bsc/version/latest"
SUBGRAPH_HEALTH_URL = "https://indexer.upgrade.thegraph.com/status"

# Jupiter API configuration
JUPITER_API_BASE_URL = "https://api.jup.ag/ultra"
JUPITER_LITE_API_BASE_URL = "https://lite-api.jup.ag"
JUPITER_LEND_API_BASE_URL = "https://dev.jup.ag"

# Network Configurations
# Solana - Helius RPC
SOLANA_RPC_URL = "https://mainnet.helius-rpc.com/?api-key=3e4462af-f2b9-4a36-9387-a649c63273d3"
SOLANA_DEVNET_RPC_URL = "https://devnet.helius-rpc.com/?api-key=3e4462af-f2b9-4a36-9387-a649c63273d3"
SOLANA_CLUSTER = "mainnet-beta"

# BSC - Infura
BSC_MAINNET_RPC_URL = "https://bsc-mainnet.infura.io/v3/402b910bd7e24d2a866ac48ab3741e75"
BSC_TESTNET_RPC_URL = "https://bsc-testnet.infura.io/v3/402b910bd7e24d2a866ac48ab3741e75"

# Privy Configuration (for TRON wallet creation)
PRIVY_APP_ID = "cmfw7skmh00lfjx0cg4zompxp"
# Note: PRIVY_APP_SECRET should be set as a secret, not in vars
# Run: wrangler secret put PRIVY_APP_SECRET
# (Input your Privy App Secret from dashboard)

# TRON Network Configuration
TRONGRID_API_KEY = "7bcda08c-dc0e-4aec-9645-d153d5ea258d"

# ⚠️ Sensitive information should use secrets instead of vars
# Run this command to set secret:
# wrangler secret put SUBGRAPH_AUTH_TOKEN
# （输入你的 Bearer token，例如 <The Graph Api KEY> ）

# 🔧 Production AI binding - Enabled for AI functionality
[ai]
binding = "AI"

# ✅ Database configuration - Mars Database
[[d1_databases]]
binding = "D1_DATABASE"  # Matches env.D1_DATABASE in code
database_name = "mars-liquid-database"
database_id = "db7389fb-ea41-46d3-87aa-5d283618d113"
migrations_dir = "drizzle"

# ✅ KV Namespaces for caching
[[kv_namespaces]]
binding = "KV"
id = "f68574afd1684065b575ca4635be1050"
preview_id = "df3f475a32684aaf9843e876628171ca"

# ✅ Hyperdrive configuration for Neon PostgreSQL
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "598eb138eef849c9a5682f494f20e753"  # mars-neon-db
localConnectionString = "postgresql://localhost:5432/postgres"  # Local dev fallback

# ✅ Durable Objects Configuration
[durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "D1Agent" },
  { name = "SUBSTREAMS_INDEXER_CONTAINER", class_name = "SubstreamsIndexerContainer" }
]

# Note: Migrations removed - Durable Objects already exist in production
[[migrations]]
 tag = "v1"
 new_sqlite_classes = ["D1Agent"]

[[migrations]]
 tag = "v2"
 new_classes = ["SubstreamsIndexerContainer"]

[[migrations]]
 tag = "v3"
 new_sqlite_classes = ["SubstreamsIndexerContainer"]

# ✅ Cloudflare Containers Configuration
# Substreams Indexer runs as a containerized Durable Object
[[containers]]
class_name = "SubstreamsIndexerContainer"
image = "./Dockerfile"
image_build_context = "./container_src"
max_instances = 1
instance_type = "basic"
name = "mars-substreams-indexer"

# Build-time variables (passed to docker build as ARG) - non-sensitive only
[containers.image_vars]
RUST_LOG = "debug"
SUBSTREAMS_ENDPOINT = "mainnet.sol.streamingfast.io:443"
START_BLOCK = "373471279"
OUTPUT_MODULE = "map_vault_events"

# Note: Sensitive data (DATABASE_URL, SUBSTREAMS_API_TOKEN) should be:
# 1. Stored in .env.substreams file in container_src/ (copied during build)
# 2. Or injected at runtime via Cloudflare secrets/environment
# This keeps credentials out of the Docker image layers

# 🔧 Development environment configuration (minimal for testing)
[env.development]
[env.development.vars]
NODE_ENV = "development"
LOG_LEVEL = "debug"
ENABLE_CONSOLE_LOGS = "true"
ENABLE_STRUCTURED_LOGS = "true"
# Development can use different RPC endpoints or test networks
SUBGRAPH_URL = "https://api.studio.thegraph.com/query/114739/mars-dex-bsc-testnet/version/latest"
SUBGRAPH_HEALTH_URL = "https://indexer.upgrade.thegraph.com/status"

# Jupiter API configuration for development
JUPITER_API_BASE_URL = "https://api.jup.ag/ultra"
JUPITER_LITE_API_BASE_URL = "https://lite-api.jup.ag"
JUPITER_LEND_API_BASE_URL = "https://dev.jup.ag"

# Network Configurations for Development
# Solana - Helius RPC
SOLANA_RPC_URL = "https://mainnet.helius-rpc.com/?api-key=3e4462af-f2b9-4a36-9387-a649c63273d3"
SOLANA_DEVNET_RPC_URL = "https://devnet.helius-rpc.com/?api-key=3e4462af-f2b9-4a36-9387-a649c63273d3"
SOLANA_CLUSTER = "mainnet-beta"

# BSC - Infura
BSC_MAINNET_RPC_URL = "https://bsc-mainnet.infura.io/v3/402b910bd7e24d2a866ac48ab3741e75"
BSC_TESTNET_RPC_URL = "https://bsc-testnet.infura.io/v3/402b910bd7e24d2a866ac48ab3741e75"

[env.development.ai]
binding = "AI"

[[env.development.d1_databases]]
binding = "D1_DATABASE"
database_name = "mars-liquid-database"
database_id = "db7389fb-ea41-46d3-87aa-5d283618d113"
migrations_dir = "drizzle"

[[env.development.kv_namespaces]]
binding = "KV"
id = "df3f475a32684aaf9843e876628171ca"

[env.development.durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "D1Agent" }
]

# ✅ Production environment configuration
[env.production]
[env.production.vars]
NODE_ENV = "production"
LOG_LEVEL = "warn"
ENABLE_CONSOLE_LOGS = "false"
ENABLE_STRUCTURED_LOGS = "true"
SUBGRAPH_URL = "https://api.studio.thegraph.com/query/114739/enty-square-bsc/version/latest"
SUBGRAPH_HEALTH_URL = "https://indexer.upgrade.thegraph.com/status"

# Jupiter API configuration for production
JUPITER_API_BASE_URL = "https://api.jup.ag/ultra"
JUPITER_LITE_API_BASE_URL = "https://lite-api.jup.ag" 
JUPITER_LEND_API_BASE_URL = "https://dev.jup.ag"

# Network Configurations for Production
# Solana - Helius RPC
SOLANA_RPC_URL = "https://mainnet.helius-rpc.com/?api-key=3e4462af-f2b9-4a36-9387-a649c63273d3"
SOLANA_DEVNET_RPC_URL = "https://devnet.helius-rpc.com/?api-key=3e4462af-f2b9-4a36-9387-a649c63273d3"
SOLANA_CLUSTER = "mainnet-beta"

# BSC - Infura
BSC_MAINNET_RPC_URL = "https://bsc-mainnet.infura.io/v3/402b910bd7e24d2a866ac48ab3741e75"
BSC_TESTNET_RPC_URL = "https://bsc-testnet.infura.io/v3/402b910bd7e24d2a866ac48ab3741e75"

[env.production.ai]
binding = "AI"

[[env.production.kv_namespaces]]
binding = "KV"
id = "f68574afd1684065b575ca4635be1050"