[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
mars = "9tbZc9Vk7wuq3TWBzZqbWZufZASc3YkQUNB1mGg92LZX"

[programs.mainnet]
mars = "Dfr6zir7nV2DWduqhtHNdkJn4mMxHf9G8muQSatiZ1k9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./phantom-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false
