[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[build]
cargo_args = ["--release"]

[programs.localnet]
mars = "9A2JwsP3yrP4TPAoRa2kqmBWwtfKfT73syPqSaSCLPXJ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "user.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "4sN8PnN2ki2W4TFXAfzR645FWs8nimmsYeNtxM8RBK6A"
program = "./artifacts/spl_token_faucet.so"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./artifacts/metadata_program.so"

[[test.genesis]]
address = "556qRmYYuXwFVXYVztx3HvMzePDBchuXMDLBWVzzaG4M"
program = "./target/deploy/mars.so"
